import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions - ViralGenie",
  description: "Terms and conditions for using ViralGenie's AI-powered content creation and growth platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-center mb-12 text-foreground">
            Terms & Conditions
          </h1>
          
          <div className="space-y-8 text-muted-foreground">
            <p className="text-lg leading-relaxed">
              Welcome to ViralGenie. By using our website and services, you agree to these Terms & Conditions. 
              If you disagree with any part, please do not use ViralGenie.
            </p>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. Use of Service</h2>
              <p className="mb-4">
                ViralGenie is an AI-powered tool that provides content ideation, coaching, and growth insights. You must:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Be at least 13 years old</li>
                <li>Provide accurate information when registering</li>
                <li>Use the service lawfully and respectfully</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. Account & Subscription</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You are responsible for your account credentials.</li>
                <li>Subscription plans are billed monthly or annually.</li>
                <li>You can cancel anytime; no refunds for partial periods.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. Intellectual Property</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>All content generated by our AI is yours to use, edit, and publish.</li>
                <li>ViralGenie owns all rights to the underlying software, designs, and branding.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. User Content</h2>
              <p className="mb-4">
                You retain ownership of any input you provide. By using our service, you grant us a license to 
                process and analyze this content for improving results.
              </p>
              <p className="mb-4">You agree not to upload:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Harmful, illegal, or plagiarized content</li>
                <li>Malicious code, bots, or spam</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. Termination</h2>
              <p>
                We may suspend or terminate your account if you violate these terms, abuse the system, or act maliciously.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Disclaimers</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>ViralGenie provides no guarantee of performance or follower growth.</li>
                <li>The AI's outputs are based on trends and predictions and may not always be accurate.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. Limitation of Liability</h2>
              <p>
                We are not liable for any direct or indirect damages arising from use of our service, 
                including content loss, account bans, or revenue loss.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Modifications</h2>
              <p>
                We may update these terms from time to time. Continued use after changes means you accept the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Contact</h2>
              <p>
                For support or questions, reach out to{" "}
                <a href="mailto:support@viralgenie.io" className="text-primary hover:underline">
                  support@viralgenie.io
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
} 